### ISSUE TITLE
[feature request] Add terminals hyperlinks

### ISSUE THREAD

**Issue by tamwile** [varyg1001/nyaaup#14]
Hi, could you add hyperlinks in the rich output ?

[Real working hyperlinks in the terminal with Rich](https://www.willmcgugan.com/blog/tech/post/real-working-hyperlinks-in-the-terminal-with-rich/)

**Comment by varyg1001** [comment]
It was added but I removed it because doesn't really worked for me. One terminal I use just did nothing and windows terminal support links anyway.

**Comment by tamwile** [comment]
The hyperlinks work depending on the terminal, your terminal has to implement the standard.
For example, kitty understand terminal hyperlinks.
If windows terminal understand hyperlinks without explicitely saying this is one, then it means it's parsing the output to find a schema such as "https?://..." (which is not standard, but why not).

As you want, this is a personal tool for you primarily, but i would advise to add it if it doesn't complexify the application ([link] [/link]), and doesn't add maintenance cost.

**Comment by varyg1001** [comment]
Btw most of the links still has the link tag (I though I removed theme but not really).
Like here:
https://github.com/varyg1001/nyaaup/blob/dacd9184a548de2c6deee3c9ed036d9ffa554dbf/nyaaup/utils.py#L337

But I kept the link in the tag because it's only good for me the link If I use win terminal whitout tmux.
